# config
cover: /static/img/asteroids.jpg
# logo: http://www.gravatar.com/avatar/6d5382e5dccca4c7f865de76dadc136a.png?s=150
bio: "Jico is a young self-starter living in Brooklyn, NY. Since recently moving to the city, he's: become a huge food snob, adopted a decievingly large-looking tiny puppy, and is rapidly falling in love with front-end tech. He currently works as a developer at Crowdtap."

# Content
excerpt_link: Read more

# Miscellaneous
rss:
